height: 500
menubar: true
toolbar:
  - undo redo | styles | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media | forecolor backcolor emoticons
plugins:
  - insertdatetime lists media table code help wordcount advlist autolink link image lists charmap preview anchor pagebreak searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media table emoticons template help

images_upload_url: '/upload_file'
